# coding: utf-8

Topic.create(:user_id => 2, :title => "TWWSG", :content => "3327RERYE5374537")
Topic.create(:user_id => 2, :title => "LUUIYMY", :content => "LLUL7I642TWETWCNC")
Topic.create(:user_id => 2, :title => "2525", :content => "JFHJWTWTE346346BXBSSDWEQWTRWTW")
Topic.create(:user_id => 2, :title => "MH425", :content => "3DGHSHSH635HDFHSRY")
Topic.create(:user_id => 2, :title => "08FGDF7807", :content => "AHA58484684SHAHAAHAH")
Topic.create(:user_id => 2, :title => "85863SHSF", :content => "EYWSAGAGAHAF363573YUETUTE")
Topic.create(:user_id => 2, :title => "TWWSG", :content => "3327RERYE5374537")
Topic.create(:user_id => 2, :title => "LUUIYMY", :content => "LLUL7I642TWETWCNC")
Topic.create(:user_id => 2, :title => "2525", :content => "JFHJWTWTE346346BXBSSDWEQWTRWTW")
Topic.create(:user_id => 2, :title => "MH425", :content => "3DGHSHSH635HDFHSRY")
Topic.create(:user_id => 2, :title => "08FGDF7807", :content => "AHA58484684SHAHAAHAH")
Topic.create(:user_id => 2, :title => "85863SHSF", :content => "EYWSAGAGAHAF363573YUETUTE")
Topic.create(:user_id => 2, :title => "TWWSG", :content => "3327RERYE5374537")
Topic.create(:user_id => 2, :title => "LUUIYMY", :content => "LLUL7I642TWETWCNC")
Topic.create(:user_id => 2, :title => "2525", :content => "JFHJWTWTE346346BXBSSDWEQWTRWTW")
Topic.create(:user_id => 2, :title => "MH425", :content => "3DGHSHSH635HDFHSRY")
Topic.create(:user_id => 2, :title => "08FGDF7807", :content => "AHA58484684SHAHAAHAH")
Topic.create(:user_id => 2, :title => "85863SHSF", :content => "EYWSAGAGAHAF363573YUETUTE")


Topic.create(:user_id => 3, :title => "T73G", :content => "3327RERYE5374537")
Topic.create(:user_id => 3, :title => "L262MY", :content => "LLUL3763ETWCNC")
Topic.create(:user_id => 4, :title => "2525", :content => "JFHJWTWTE346346BXBSSDWEQWTRWTW")
Topic.create(:user_id => 3, :title => "MH425", :content => "3DGHSHSH635HDFHSRY")
Topic.create(:user_id => 3, :title => "08FGDF7807", :content => "AHA58484684SHAHAAHAH")
Topic.create(:user_id => 2, :title => "85863SHSF", :content => "EYWSAGAGAHAF363573YUETUTE")
# ========================= init Section, Node =========================

# s1 = Section.create(:name => "Ruby")
# Node.create(:name => "Ruby",:summary => "...", :section_id => s1.id)
# Node.create(:name => "Ruby on Rails",:summary => "...", :section_id => s1.id)
# Node.create(:name => "Gem",:summary => "...", :section_id => s1.id)
# s2 = Section.create(:name => "Web Development")
# Node.create(:name => "Python",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Javascript",:summary => "...", :section_id => s2.id)
# Node.create(:name => "CoffeeScript",:summary => "...", :section_id => s2.id)
# Node.create(:name => "HAML",:summary => "...", :section_id => s2.id)
# Node.create(:name => "SASS",:summary => "...", :section_id => s2.id)
# Node.create(:name => "MongoDB",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Redis",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Git",:summary => "...", :section_id => s2.id)
# Node.create(:name => "MySQL",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Hadoop",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Google",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Java",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Tornado",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Linux",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Nginx",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Apache",:summary => "...", :section_id => s2.id)
# Node.create(:name => "Cloud",:summary => "...", :section_id => s2.id)
# s6 = Section.create(:name => "Ruby China")
# Node.create(:name => "公告",:summary => "...", :section_id => s6.id)
# Node.create(:name => "反馈",:summary => "...", :section_id => s6.id)
# Node.create(:name => "开发",:summary => "...", :section_id => s6.id)
# SiteNode.create(:name => "国内商业网站", :sort => 100)
# SiteNode.create(:name => "国外著名网站", :sort => 99)
# SiteNode.create(:name => "Ruby 社区网站", :sort => 98)
# SiteNode.create(:name => "技术博客", :sort => 97)
# SiteNode.create(:name => "Ruby 开源项目", :sort => 96)
# SiteNode.create(:name => "国内企业", :sort => 95)
# SiteNode.create(:name => "其他", :sort => 94)

